<#
.SYNOPSIS
    Generates a simple HTML and/or Markdown report from windows_patch_status CSV output.

.DESCRIPTION
    This script reads the CSV file produced by windows_patch_status.ps1 and generates:
      - A Markdown report (optional)
      - An HTML report (optional)

    The report includes:
      - Overall summary (host count, hosts with pending reboot, total missing updates)
      - Per-host table of patch status

.PARAMETER InputPath
    Path to the CSV file generated by windows_patch_status.ps1.

.PARAMETER MarkdownOutputPath
    Path to write a Markdown report. If not specified, Markdown is not generated.

.PARAMETER HtmlOutputPath
    Path to write an HTML report. If not specified, HTML is not generated.

.EXAMPLE
    .\windows_patch_status_report.ps1 -InputPath .\reports\windows_patch_status.csv `
        -MarkdownOutputPath .\reports\windows_patch_status_report.md

.EXAMPLE
    .\windows_patch_status_report.ps1 -InputPath .\reports\windows_patch_status.csv `
        -HtmlOutputPath .\reports\windows_patch_status_report.html `
        -MarkdownOutputPath .\reports\windows_patch_status_report.md
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]
    $InputPath,

    [string]
    $MarkdownOutputPath,

    [string]
    $HtmlOutputPath
)

if (-not (Test-Path $InputPath)) {
    throw "Input CSV file not found: $InputPath"
}

Write-Verbose "Reading CSV from $InputPath"
$data = Import-Csv -Path $InputPath

if (-not $data -or $data.Count -eq 0) {
    throw "No rows found in input CSV. Nothing to report."
}

# Compute summary
$totalHosts              = $data.Count
$hostsPendingReboot      = ($data | Where-Object { $_.PendingReboot -eq 'True' }).Count
$totalMissingUpdates     = ($data | Measure-Object -Property MissingUpdateCount -Sum).Sum
$totalCriticalMissing    = ($data | Measure-Object -Property CriticalMissingCount -Sum).Sum
$totalSecurityMissing    = ($data | Measure-Object -Property SecurityMissingCount -Sum).Sum

$generatedUtc = (Get-Date).ToUniversalTime().ToString("s") + "Z"

# Helper to ensure directory exists
function Ensure-ParentDirectory {
    param(
        [Parameter(Mandatory = $true)]
        [string] $Path
    )

    $full = [System.IO.Path]::GetFullPath($Path)
    $dir  = [System.IO.Path]::GetDirectoryName($full)

    if (-not [string]::IsNullOrWhiteSpace($dir) -and -not (Test-Path $dir)) {
        New-Item -Path $dir -ItemType Directory -Force | Out-Null
    }

    return $full
}

# Generate Markdown report
if ($MarkdownOutputPath) {
    $mdFull = Ensure-ParentDirectory -Path $MarkdownOutputPath
    Write-Verbose "Generating Markdown report at $mdFull"

    $mdLines = @()

    $mdLines += "# Windows Patch Status Report"
    $mdLines += ""
    $mdLines += "- **Generated (UTC):** $generatedUtc"
    $mdLines += "- **Source CSV:** `$(Split-Path -Leaf $InputPath)`"
    $mdLines += ""
    $mdLines += "## 1. Summary"
    $mdLines += ""
    $mdLines += "- Total hosts: **$totalHosts**"
    $mdLines += "- Hosts with pending reboot: **$hostsPendingReboot**"
    $mdLines += "- Total missing updates (all hosts): **$totalMissingUpdates**"
    $mdLines += "- Critical missing updates (all hosts): **$totalCriticalMissing**"
    $mdLines += "- Security missing updates (all hosts): **$totalSecurityMissing**"
    $mdLines += ""
    $mdLines += "## 2. Per-Host Patch Status"
    $mdLines += ""
    $mdLines += "| Computer | OS Caption | Version | Pending Reboot | Missing | Critical | Security | Sample Missing Updates |"
    $mdLines += "|----------|-----------|---------|----------------|---------|----------|----------|------------------------|"

    foreach ($row in $data) {
        $computer  = $row.ComputerName
        $os        = $row.OSCaption
        $ver       = $row.OSVersion
        $pending   = $row.PendingReboot
        $missing   = $row.MissingUpdateCount
        $crit      = $row.CriticalMissingCount
        $sec       = $row.SecurityMissingCount
        $sample    = $row.SampleMissingUpdates

        # Escape pipe characters in sample text
        if ($sample) {
            $sample = $sample -replace "\|", "\`|"
        }

        $mdLines += "| $computer | $os | $ver | $pending | $missing | $crit | $sec | $sample |"
    }

    $mdLines += ""
    $mdLines += "---"
    $mdLines += "_Generated by windows_patch_status_report.ps1_"
    $mdLines += ""

    $mdLines -join "`r`n" | Out-File -FilePath $mdFull -Encoding UTF8 -Force
    Write-Host "Markdown report written to: $mdFull"
}

# Generate HTML report
if ($HtmlOutputPath) {
    $htmlFull = Ensure-ParentDirectory -Path $HtmlOutputPath
    Write-Verbose "Generating HTML report at $htmlFull"

    $html = @()
    $html += "<!DOCTYPE html>"
    $html += "<html lang='en'>"
    $html += "<head>"
    $html += "  <meta charset='UTF-8' />"
    $html += "  <title>Windows Patch Status Report</title>"
    $html += "  <style>"
    $html += "    body { font-family: Arial, sans-serif; margin: 20px; }"
    $html += "    h1, h2 { color: #333; }"
    $html += "    table { border-collapse: collapse; width: 100%; }"
    $html += "    th, td { border: 1px solid #ccc; padding: 6px 8px; font-size: 13px; }"
    $html += "    th { background-color: #f0f0f0; }"
    $html += "    tr:nth-child(even) { background-color: #fafafa; }"
    $html += "  </style>"
    $html += "</head>"
    $html += "<body>"
    $html += "  <h1>Windows Patch Status Report</h1>"
    $html += "  <p><strong>Generated (UTC):</strong> $generatedUtc<br/>"
    $html += "     <strong>Source CSV:</strong> $(Split-Path -Leaf $InputPath)</p>"
    $html += ""
    $html += "  <h2>1. Summary</h2>"
    $html += "  <ul>"
    $html += "    <li>Total hosts: <strong>$totalHosts</strong></li>"
    $html += "    <li>Hosts with pending reboot: <strong>$hostsPendingReboot</strong></li>"
    $html += "    <li>Total missing updates (all hosts): <strong>$totalMissingUpdates</strong></li>"
    $html += "    <li>Critical missing updates (all hosts): <strong>$totalCriticalMissing</strong></li>"
    $html += "    <li>Security missing updates (all hosts): <strong>$totalSecurityMissing</strong></li>"
    $html += "  </ul>"
    $html += ""
    $html += "  <h2>2. Per-Host Patch Status</h2>"
    $html += "  <table>"
    $html += "    <thead>"
    $html += "      <tr>"
    $html += "        <th>Computer</th>"
    $html += "        <th>OS Caption</th>"
    $html += "        <th>Version</th>"
    $html += "        <th>Pending Reboot</th>"
    $html += "        <th>Missing</th>"
    $html += "        <th>Critical</th>"
    $html += "        <th>Security</th>"
    $html += "        <th>Sample Missing Updates</th>"
    $html += "      </tr>"
    $html += "    </thead>"
    $html += "    <tbody>"

    foreach ($row in $data) {
        $computer  = [System.Web.HttpUtility]::HtmlEncode($row.ComputerName)
        $os        = [System.Web.HttpUtility]::HtmlEncode($row.OSCaption)
        $ver       = [System.Web.HttpUtility]::HtmlEncode($row.OSVersion)
        $pending   = [System.Web.HttpUtility]::HtmlEncode($row.PendingReboot)
        $missing   = [System.Web.HttpUtility]::HtmlEncode($row.MissingUpdateCount)
        $crit      = [System.Web.HttpUtility]::HtmlEncode($row.CriticalMissingCount)
        $sec       = [System.Web.HttpUtility]::HtmlEncode($row.SecurityMissingCount)
        $sample    = [System.Web.HttpUtility]::HtmlEncode($row.SampleMissingUpdates)

        $html += "      <tr>"
        $html += "        <td>$computer</td>"
        $html += "        <td>$os</td>"
        $html += "        <td>$ver</td>"
        $html += "        <td>$pending</td>"
        $html += "        <td>$missing</td>"
        $html += "        <td>$crit</td>"
        $html += "        <td>$sec</td>"
        $html += "        <td>$sample</td>"
        $html += "      </tr>"
    }

    $html += "    </tbody>"
    $html += "  </table>"
    $html += "  <hr/>"
    $html += "  <p><em>Generated by windows_patch_status_report.ps1</em></p>"
    $html += "</body>"
    $html += "</html>"

    $html -join "`r`n" | Out-File -FilePath $htmlFull -Encoding UTF8 -Force
    Write-Host "HTML report written to: $htmlFull"
}

if (-not $MarkdownOutputPath -and -not $HtmlOutputPath) {
    Write-Warning "No HtmlOutputPath or MarkdownOutputPath specified. Nothing was generated."
}
